// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: beats.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createBeat = `-- name: CreateBeat :exec
INSERT INTO beats (id, measure_id, position, subdivision)
VALUES ($1, $2, $3, $4)
`

type CreateBeatParams struct {
	ID          uuid.UUID
	MeasureID   uuid.UUID
	Position    int16
	Subdivision int16
}

func (q *Queries) CreateBeat(ctx context.Context, arg CreateBeatParams) error {
	_, err := q.db.Exec(ctx, createBeat,
		arg.ID,
		arg.MeasureID,
		arg.Position,
		arg.Subdivision,
	)
	return err
}

const listBeatsByMeasureIDs = `-- name: ListBeatsByMeasureIDs :many
SELECT id, measure_id, position, subdivision
FROM beats
WHERE measure_id = ANY($1::uuid[])
ORDER BY measure_id, position ASC
`

func (q *Queries) ListBeatsByMeasureIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]Beat, error) {
	rows, err := q.db.Query(ctx, listBeatsByMeasureIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Beat
	for rows.Next() {
		var i Beat
		if err := rows.Scan(
			&i.ID,
			&i.MeasureID,
			&i.Position,
			&i.Subdivision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBeatsByScore = `-- name: ListBeatsByScore :many
SELECT b.id, b.measure_id, b.position, b.subdivision, m.position AS measure_position
FROM beats b
JOIN measures m ON m.id = b.measure_id
WHERE m.score_id = $1
ORDER BY m.position ASC, b.position ASC
`

type ListBeatsByScoreRow struct {
	ID              uuid.UUID
	MeasureID       uuid.UUID
	Position        int16
	Subdivision     int16
	MeasurePosition int16
}

func (q *Queries) ListBeatsByScore(ctx context.Context, scoreID uuid.UUID) ([]ListBeatsByScoreRow, error) {
	rows, err := q.db.Query(ctx, listBeatsByScore, scoreID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBeatsByScoreRow
	for rows.Next() {
		var i ListBeatsByScoreRow
		if err := rows.Scan(
			&i.ID,
			&i.MeasureID,
			&i.Position,
			&i.Subdivision,
			&i.MeasurePosition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
