// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: hits.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const insertHit = `-- name: InsertHit :exec
INSERT INTO hits (beat_id, part_id, step_index, velocity, ornament)
VALUES ($1, $2, $3, $4, $5)
`

type InsertHitParams struct {
	BeatID    uuid.UUID
	PartID    PartID
	StepIndex int16
	Velocity  Velocity
	Ornament  *Ornament
}

func (q *Queries) InsertHit(ctx context.Context, arg InsertHitParams) error {
	_, err := q.db.Exec(ctx, insertHit,
		arg.BeatID,
		arg.PartID,
		arg.StepIndex,
		arg.Velocity,
		arg.Ornament,
	)
	return err
}

const listHitsByBeatIDs = `-- name: ListHitsByBeatIDs :many
SELECT beat_id, part_id, step_index, velocity, ornament
FROM hits
WHERE beat_id = ANY($1::uuid[])
`

func (q *Queries) ListHitsByBeatIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]Hit, error) {
	rows, err := q.db.Query(ctx, listHitsByBeatIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Hit
	for rows.Next() {
		var i Hit
		if err := rows.Scan(
			&i.BeatID,
			&i.PartID,
			&i.StepIndex,
			&i.Velocity,
			&i.Ornament,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHitsByScore = `-- name: ListHitsByScore :many
SELECT h.beat_id, h.part_id, h.step_index, h.velocity, h.ornament,
       b.position AS beat_position, m.position AS measure_position
FROM hits h
JOIN beats b ON b.id = h.beat_id
JOIN measures m ON m.id = b.measure_id
WHERE m.score_id = $1
ORDER BY m.position ASC, b.position ASC, h.part_id, h.step_index
`

type ListHitsByScoreRow struct {
	BeatID          uuid.UUID
	PartID          PartID
	StepIndex       int16
	Velocity        Velocity
	Ornament        *Ornament
	BeatPosition    int16
	MeasurePosition int16
}

func (q *Queries) ListHitsByScore(ctx context.Context, scoreID uuid.UUID) ([]ListHitsByScoreRow, error) {
	rows, err := q.db.Query(ctx, listHitsByScore, scoreID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHitsByScoreRow
	for rows.Next() {
		var i ListHitsByScoreRow
		if err := rows.Scan(
			&i.BeatID,
			&i.PartID,
			&i.StepIndex,
			&i.Velocity,
			&i.Ornament,
			&i.BeatPosition,
			&i.MeasurePosition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
