// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: measures.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createMeasure = `-- name: CreateMeasure :exec
INSERT INTO measures (id, score_id, position) VALUES ($1, $2, $3)
`

type CreateMeasureParams struct {
	ID       uuid.UUID
	ScoreID  uuid.UUID
	Position int16
}

func (q *Queries) CreateMeasure(ctx context.Context, arg CreateMeasureParams) error {
	_, err := q.db.Exec(ctx, createMeasure, arg.ID, arg.ScoreID, arg.Position)
	return err
}

const deleteMeasuresByScore = `-- name: DeleteMeasuresByScore :exec
DELETE FROM measures WHERE score_id = $1
`

func (q *Queries) DeleteMeasuresByScore(ctx context.Context, scoreID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMeasuresByScore, scoreID)
	return err
}

const listFirstMeasureForScores = `-- name: ListFirstMeasureForScores :many
SELECT id, score_id, position
FROM measures
WHERE score_id = ANY($1::uuid[]) AND position = 0
`

func (q *Queries) ListFirstMeasureForScores(ctx context.Context, dollar_1 []uuid.UUID) ([]Measure, error) {
	rows, err := q.db.Query(ctx, listFirstMeasureForScores, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Measure
	for rows.Next() {
		var i Measure
		if err := rows.Scan(&i.ID, &i.ScoreID, &i.Position); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMeasuresByScore = `-- name: ListMeasuresByScore :many
SELECT id, score_id, position
FROM measures
WHERE score_id = $1
ORDER BY position ASC
`

func (q *Queries) ListMeasuresByScore(ctx context.Context, scoreID uuid.UUID) ([]Measure, error) {
	rows, err := q.db.Query(ctx, listMeasuresByScore, scoreID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Measure
	for rows.Next() {
		var i Measure
		if err := rows.Scan(&i.ID, &i.ScoreID, &i.Position); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMeasuresByScoreLimited = `-- name: ListMeasuresByScoreLimited :many
SELECT id, score_id, position
FROM measures
WHERE score_id = $1
ORDER BY position ASC
LIMIT $2
`

type ListMeasuresByScoreLimitedParams struct {
	ScoreID uuid.UUID
	Limit   int32
}

func (q *Queries) ListMeasuresByScoreLimited(ctx context.Context, arg ListMeasuresByScoreLimitedParams) ([]Measure, error) {
	rows, err := q.db.Query(ctx, listMeasuresByScoreLimited, arg.ScoreID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Measure
	for rows.Next() {
		var i Measure
		if err := rows.Scan(&i.ID, &i.ScoreID, &i.Position); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
