// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Ornament string

const (
	OrnamentFLAM Ornament = "FLAM"
	OrnamentDRAG Ornament = "DRAG"
	OrnamentRUFF Ornament = "RUFF"
)

func (e *Ornament) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Ornament(s)
	case string:
		*e = Ornament(s)
	default:
		return fmt.Errorf("unsupported scan type for Ornament: %T", src)
	}
	return nil
}

type NullOrnament struct {
	Ornament Ornament
	Valid    bool // Valid is true if Ornament is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrnament) Scan(value interface{}) error {
	if value == nil {
		ns.Ornament, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Ornament.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrnament) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Ornament), nil
}

func (e Ornament) Valid() bool {
	switch e {
	case OrnamentFLAM,
		OrnamentDRAG,
		OrnamentRUFF:
		return true
	}
	return false
}

type PartID string

const (
	PartIDCRASH  PartID = "CRASH"
	PartIDRIDE   PartID = "RIDE"
	PartIDHHOPEN PartID = "HH_OPEN"
	PartIDHH     PartID = "HH"
	PartIDHITOM  PartID = "HI_TOM"
	PartIDMIDTOM PartID = "MID_TOM"
	PartIDSNARE  PartID = "SNARE"
	PartIDLOTOM  PartID = "LO_TOM"
	PartIDBD     PartID = "BD"
)

func (e *PartID) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PartID(s)
	case string:
		*e = PartID(s)
	default:
		return fmt.Errorf("unsupported scan type for PartID: %T", src)
	}
	return nil
}

type NullPartID struct {
	PartID PartID
	Valid  bool // Valid is true if PartID is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPartID) Scan(value interface{}) error {
	if value == nil {
		ns.PartID, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PartID.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPartID) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PartID), nil
}

func (e PartID) Valid() bool {
	switch e {
	case PartIDCRASH,
		PartIDRIDE,
		PartIDHHOPEN,
		PartIDHH,
		PartIDHITOM,
		PartIDMIDTOM,
		PartIDSNARE,
		PartIDLOTOM,
		PartIDBD:
		return true
	}
	return false
}

type Velocity string

const (
	VelocityNORMAL Velocity = "NORMAL"
	VelocityACCENT Velocity = "ACCENT"
	VelocityGHOST  Velocity = "GHOST"
)

func (e *Velocity) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Velocity(s)
	case string:
		*e = Velocity(s)
	default:
		return fmt.Errorf("unsupported scan type for Velocity: %T", src)
	}
	return nil
}

type NullVelocity struct {
	Velocity Velocity
	Valid    bool // Valid is true if Velocity is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVelocity) Scan(value interface{}) error {
	if value == nil {
		ns.Velocity, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Velocity.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVelocity) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Velocity), nil
}

func (e Velocity) Valid() bool {
	switch e {
	case VelocityNORMAL,
		VelocityACCENT,
		VelocityGHOST:
		return true
	}
	return false
}

type Beat struct {
	ID          uuid.UUID
	MeasureID   uuid.UUID
	Position    int16
	Subdivision int16
}

type Hit struct {
	BeatID    uuid.UUID
	PartID    PartID
	StepIndex int16
	Velocity  Velocity
	Ornament  *Ornament
}

type Measure struct {
	ID       uuid.UUID
	ScoreID  uuid.UUID
	Position int16
}

type Score struct {
	ID             uuid.UUID
	Title          string
	Bpm            int16
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	SpotifyTrackID *string
}
