// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scores.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countMeasures = `-- name: CountMeasures :one
SELECT COUNT(*)::int AS measures_count
FROM measures
WHERE score_id = $1
`

func (q *Queries) CountMeasures(ctx context.Context, scoreID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countMeasures, scoreID)
	var measures_count int32
	err := row.Scan(&measures_count)
	return measures_count, err
}

const countMeasuresForScores = `-- name: CountMeasuresForScores :many
SELECT score_id, COUNT(*)::int AS measures_count
FROM measures
WHERE score_id = ANY($1::uuid[])
GROUP BY score_id
`

type CountMeasuresForScoresRow struct {
	ScoreID       uuid.UUID
	MeasuresCount int32
}

func (q *Queries) CountMeasuresForScores(ctx context.Context, dollar_1 []uuid.UUID) ([]CountMeasuresForScoresRow, error) {
	rows, err := q.db.Query(ctx, countMeasuresForScores, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountMeasuresForScoresRow
	for rows.Next() {
		var i CountMeasuresForScoresRow
		if err := rows.Scan(&i.ScoreID, &i.MeasuresCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createScore = `-- name: CreateScore :exec
INSERT INTO scores (id, title, bpm, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateScoreParams struct {
	ID        uuid.UUID
	Title     string
	Bpm       int16
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) CreateScore(ctx context.Context, arg CreateScoreParams) error {
	_, err := q.db.Exec(ctx, createScore,
		arg.ID,
		arg.Title,
		arg.Bpm,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteScore = `-- name: DeleteScore :execrows
DELETE FROM scores WHERE id = $1
`

func (q *Queries) DeleteScore(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteScore, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findScoreIDByTitle = `-- name: FindScoreIDByTitle :one
SELECT id FROM scores WHERE title = $1 LIMIT 1
`

func (q *Queries) FindScoreIDByTitle(ctx context.Context, title string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, findScoreIDByTitle, title)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getScore = `-- name: GetScore :one
SELECT id, title, bpm, created_at, updated_at
FROM scores
WHERE id = $1
`

func (q *Queries) GetScore(ctx context.Context, id uuid.UUID) (Score, error) {
	row := q.db.QueryRow(ctx, getScore, id)
	var i Score
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Bpm,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listScores = `-- name: ListScores :many
SELECT id, title, bpm, created_at, updated_at
FROM scores
ORDER BY updated_at DESC
LIMIT $1 OFFSET $2
`

type ListScoresParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListScores(ctx context.Context, arg ListScoresParams) ([]Score, error) {
	rows, err := q.db.Query(ctx, listScores, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Score
	for rows.Next() {
		var i Score
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Bpm,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScoreMeta = `-- name: UpdateScoreMeta :execrows
UPDATE scores
SET title = $2, bpm = $3, updated_at = $4
WHERE id = $1
`

type UpdateScoreMetaParams struct {
	ID        uuid.UUID
	Title     string
	Bpm       int16
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) UpdateScoreMeta(ctx context.Context, arg UpdateScoreMetaParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateScoreMeta,
		arg.ID,
		arg.Title,
		arg.Bpm,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
